"""add_digest_table

Revision ID: 53f5fe358d4b
Revises: 1ec4c0eb879f
Create Date: 2025-12-07 10:43:38.907400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f5fe358d4b'
down_revision: Union[str, Sequence[str], None] = '1ec4c0eb879f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_digests_user_created', 'digests', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_digests_user_id', 'digests', ['user_id'], unique=False)
    op.create_index(op.f('ix_digests_user_id'), 'digests', ['user_id'], unique=False)
    op.alter_column('notes', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('notes', 'confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('notes', 'transcription_duration',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('notes', 'model_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_notes_folder_path'), 'notes', ['folder_path'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_folder_path'), table_name='notes')
    op.alter_column('notes', 'model_version',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('notes', 'transcription_duration',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('notes', 'confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('notes', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_digests_user_id'), table_name='digests')
    op.drop_index('idx_digests_user_id', table_name='digests')
    op.drop_index('idx_digests_user_created', table_name='digests')
    op.drop_table('digests')
    # ### end Alembic commands ###
